version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hiremate-backend
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/service-account-key.json:/app/service-account-key.json:ro
      - ./backend/assets:/app/assets
    networks:
      - hiremate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Pass build arguments from .env file
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
    container_name: hiremate-frontend
    expose:
      - "4000"
    depends_on:
      - backend
    networks:
      - hiremate-network
    restart: unless-stopped

  # Nginx Reverse Proxy for Domain Binding
  nginx:
    image: nginx:alpine
    container_name: hiremate-nginx
    ports:
      - "80:80"
      - "443:443"  # For HTTPS
    volumes:
      - ./nginx-production.conf:/etc/nginx/conf.d/default.conf:ro
      # Uncomment these lines when you have SSL certificates
      # - ./ssl/certs:/etc/ssl/certs:ro
      # - ./ssl/private:/etc/ssl/private:ro
    depends_on:
      - frontend
      - backend
    networks:
      - hiremate-network
    restart: unless-stopped

networks:
  hiremate-network:
    driver: bridge

volumes:
  backend_assets:
    driver: local
